name: Обновление зависимостей

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Фильтр пакетов'
      target:
        description: 'Тип версии'
        default: 'latest'
        type: choice 
        options:
          - latest
          - minor
          - patch

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Обновление зависимостей
        uses: Stivo182/test@main
        with:
          filter: ${{ inputs.filter }}
          target: ${{ inputs.target }}
          message-prefix: build(deps) 
          token: ${{ secrets.PAT }}